name: "Create TFC Workspace"
description: "Creates or deletes a Terraform Cloud workspace"
inputs:
  subcommand:
    description: "Which subcommand to invoke: `create` or `delete`"
    required: true
  tfcToken:
    description: A Terraform Cloud API token with access to manage workspaces
    required: true
  orgName:
    description: The name of the Terraform Cloud organization in which to create the workspace
    required: true
  workspaceName:
    description: The name of the Terraform Cloud workspace
    required: true
runs:
  using: "docker"
  image: "docker://frostedcarbon/manage-tfc-workspace-image:latest"
  args:
    - workspace
    - ${{ inputs.subcommand }}
    - -token
    - ${{ inputs.tfcToken }}
    - -org
    - ${{ inputs.orgName }}
    - -workspace
    - ${{ inputs.workspaceName }}
